//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningGameV1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusic
    {
        public int musicID { get; set; }
        public string musicName { get; set; }
        public string musicPath { get; set; }
    }
}
